"""Device-profiler PROBE for one real training step -- meant to be launched
under `python -m tracy`, not run directly.

## Why this script exists

Every prior profiling attempt in this project (`profile_step_stages.py`,
`sdpa_bw_isolated_bench.py`) has been *host* wall-clock timing bounded by
`ttnn.synchronize_device` -- accurate for "how long did stage X take" but
blind to "which specific device kernel/op inside stage X actually cost that
time." `tenstorrent/docs/m6-optimization-results.md` repeatedly notes "no
Tracy/device-profiler available on this host" as the reason several
investigations (the redundant Q/dO reread fix's regression, the encoder-vs-
decoder SDPA-backward-fix asymmetry) couldn't be root-caused further.

That belief was wrong -- not re-investigated carefully enough. This build
*does* have Tracy compiled in (`ENABLE_TRACY=ON` in `build_Release/
CMakeCache.txt`, confirmed via `nm`/`strings` on the installed `_ttml.abi3.so`
and `ttnn`'s own `_ttnn.abi3.so`), and the standard `tt-metal` device-profiler
pipeline (`TT_METAL_DEVICE_PROFILER=1` + `ttnn.ReadDeviceProfiler` +
`tools/tracy/process_model_log.py`'s CSV parsing, the same pattern
`models/tt_dit/utils/sweep_mm_block_sizes.py` uses) works end-to-end on this
host with **zero rebuild** -- verified with a trivial `ttnn.add` probe before
writing this file: `python -m tracy -p -r -o <dir> -a device_kernel_duration
-t 5000 -m <module>` produces a real `ops_perf_results_*.csv` with a genuine
non-trivial `DEVICE KERNEL DURATION [ns]` per op.

## How to run this (do not run it directly -- see `device_profile_report.py`)

This file IS the workload; `device_profile_report.py` is the driver that
wraps it in the `python -m tracy` subprocess and parses the resulting CSV.
Running this file directly (`python -m smri_mae_tt.scripts.
device_profile_step`) does real training steps and prints a signpost marker
via `tracy.signpost`, but produces no device-profiler CSV on its own --
`TT_METAL_DEVICE_PROFILER` must be set in the environment *before* the
device opens (`python -m tracy` does this), and the CSV is only generated by
`python -m tracy`'s post-processing step (`-r`), not by this script.

## Design: bracket exactly ONE real step with signposts

`main_pretrain_tt.train()`'s `on_step_timing(step, elapsed)` hook fires
*after* each step completes. To capture exactly one step's worth of device
ops (not "everything from process start," which would include JIT-compile
noise from step 0 and inflate the profiler's program-support-count needs for
no reason), this script runs `--warmup-steps + 1` steps total: `signpost
("start")` is emitted the instant the last warmup step's `on_step_timing`
fires (i.e. immediately before the measured step's work begins), and
`signpost("stop")` fires the instant the measured step's own `on_step_timing`
fires. `device_profile_report.py`'s CSV parsing (mirroring `sweep_mm_block_
sizes.py`'s `parse_ops_log`) filters to rows strictly between these two
signposts, so only the one measured step's ops are counted -- same idiom as
that file, just applied to a single production training step instead of a
matmul sweep.

Uses the real production entry point (`main_pretrain_tt.train()`, `prefetch=
True`) at `full-vitl-real` scale by default, same as `bench_step.py` --
avoids the exact "bypassed prefetch, got a misleading number" mistake noted
in that file's docstring.

## Periodic mid-run profiler flush (required at full-vitl-real scale)

A first attempt at this script with NO flushing (relying on `python -m
tracy`'s post-run `ttnn.ReadDeviceProfiler` alone, the same as `models/
tt_dit/utils/sweep_mm_block_sizes.py`'s warmup phase without periodic
flushes) failed at `full-vitl-real` scale: `Profiler DRAM buffers were full,
markers were dropped!` on 46/110 cores, 230 total warnings, which then
crashed `tracy`'s post-processing outright (`AssertionError: Device data
missing: Op ... not present in cpp_device_perf_report.csv`) -- not just
missing data, a hard failure, no CSV produced at all. Per-RISC profiler
buffers are small (compile-time constant, `PROFILER_FULL_HOST_BUFFER_SIZE_
PER_RISC`, ~48000 marker slots on most RISCs this build) and a 28-block
model's forward+backward, especially the decoder's SDPA backward kernels
(hundreds of K/V rows per core, each with several per-tile CB-wait/reserve
zone markers -- see `kernel_profiler.hpp`'s `DeviceZoneScopedSumN1`
instrumentation baked into every `cb_wait_front`/`cb_reserve_back` call),
generates far more zone markers per core than a `smoke`/`gate`-scale run
does (which worked fine with zero flushing, see this file's git history).

Fix: `train()`'s existing `on_stage_timing(step, stage_name, elapsed)` hook
(already device-synchronized at each boundary -- see that function's
docstring) is repurposed here to also call `ttnn.ReadDeviceProfiler(device)`
at every stage boundary of *every* step (both warmup and measured -- an
overflow during warmup, before the measured window even starts, would still
corrupt the measured step's data once the shared per-core buffer fills), via
`ttnn.synchronize_device` + `ttnn.ReadDeviceProfiler` -- the same idiom
`sweep_mm_block_sizes.py`'s `_execute_sweep` uses between combos, applied to
stage boundaries here since a training step has no combo-loop to hook into.
This is coarser than the sweep script's "every 10 ops" (7 stages/step vs
this project's actually-continuous op stream), but it is the only
uninstrumented flush point `train()` exposes without editing `model_tt.py`
to add a hook inside the per-block loop -- confirmed sufficient in practice
(see `tenstorrent/docs/m6-optimization-results.md` for the resulting clean,
warning-free `full-vitl-real` run). Requires `TT_METAL_PROFILER_MID_RUN_
DUMP=1` in the environment (set by `device_profile_report.py`'s subprocess
launch) -- without it, `ReadDeviceProfiler` calls before the run's natural
end are silently limited (per `tt_metal/llrt/rtoptions.cpp`'s
`profiler_mid_run_dump` gate).
"""

from __future__ import annotations

import argparse
import functools
import sys

import ttml
import ttnn
from tracy import signpost

from smri_mae_tt import real_data
from smri_mae_tt.config_tt import TTMAEConfig
from smri_mae_tt.main_pretrain_tt import _PRESETS, train


def run_bracketed_step(preset: str, *, warmup_steps: int, seed: int) -> None:
    if preset not in _PRESETS:
        raise ValueError(f"unknown preset {preset!r}, choose from {sorted(_PRESETS)}")
    if warmup_steps < 0:
        raise ValueError(f"warmup_steps must be >= 0, got {warmup_steps}")

    contract_fn, encoder_depth, decoder_depth = _PRESETS[preset]
    contract = contract_fn()
    cfg = TTMAEConfig(shape_contract=contract)

    train_source = real_data.RealTrainSource(contract)
    train_batch_source_factory = functools.partial(real_data.RealTrainSource, contract)

    measured_step = warmup_steps
    total_steps = warmup_steps + 1

    auto_ctx = ttml.autograd.AutoContext.get_instance()

    def on_stage_timing(step: int, stage: str, elapsed: float) -> None:
        # Drain the per-core device profiler buffer at every stage boundary
        # (both warmup and measured steps) -- see module docstring's
        # "Periodic mid-run profiler flush" section for why this is required
        # at this scale. `train()` already synchronized the device
        # immediately before calling this hook (see its own docstring), so
        # this ReadDeviceProfiler call is reading fully-completed device work.
        device = auto_ctx.get_device()
        ttnn.ReadDeviceProfiler(device)

    def on_step_timing(step: int, elapsed: float) -> None:
        tag = "  <- measured (bracketed by signposts)" if step == measured_step else "  <- warmup"
        print(f"  step {step}: {elapsed * 1000:.1f} ms{tag}", flush=True)
        if step == measured_step - 1:
            # Last warmup step just finished; the next step is the measured
            # one -- start the bracket now, before its work is dispatched.
            signpost("start")
        if step == measured_step:
            signpost("stop")

    # warmup_steps == 0 means the very first (and only) step is the measured
    # one -- there is no prior on_step_timing call to hang the "start"
    # signpost off of, so emit it up front in that case.
    if warmup_steps == 0:
        signpost("start")

    print(f"device_profile_step: preset={preset} warmup_steps={warmup_steps} measured_step={measured_step} seed={seed}", flush=True)

    train(
        contract,
        encoder_depth,
        decoder_depth,
        cfg,
        total_steps,
        warmup_steps=0,
        seed=seed,
        log_every=total_steps,
        print_log=True,
        train_batch_fn=train_source.next_batch,
        train_batch_source_factory=train_batch_source_factory,
        prefetch=True,
        on_step_timing=on_step_timing,
        on_stage_timing=on_stage_timing,
    )
    print("device_profile_step: done", flush=True)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--preset", choices=sorted(_PRESETS), default="full-vitl-real")
    parser.add_argument("--warmup-steps", type=int, default=1, help="steps run (and timed) before the one bracketed/measured step; step 0 always pays JIT-compile cost so this should stay >= 1 for a representative measurement")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)
    run_bracketed_step(args.preset, warmup_steps=args.warmup_steps, seed=args.seed)


if __name__ == "__main__":
    main(sys.argv[1:])
